spring.application.name=reports-management

# ===========================================
# SERVER
# ===========================================
server.port=8080

# ===========================================
# MYSQL CONFIGURATION
# ===========================================
spring.datasource.url=jdbc:mysql://localhost:3306/reportdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===========================================
# JPA / HIBERNATE
# ===========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================================
# MONGODB CONFIGURATION
# ===========================================
spring.data.mongodb.uri=mongodb://localhost:27017/reportdb

# ===========================================
# SWAGGER
# ===========================================
springdoc.swagger-ui.path=/swagger-ui.html

# ===========================================
# LOGGING
# ===========================================
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# ===========================================
# ACTUATOR
# ===========================================
management.endpoints.web.exposure.include=health,info
